language: go

go:
  - 1.11.x
script: make test config config_test.yaml

services:
  - mysql

dist: bionic

#env:
#  global:
#    - MUXIKSTACK_DB_USERNAME=root
#    - MUXIKSTACK_DB_PASSWORD=""

before_script:
  - mysql -u root --password="" < db.sql
