language: go

go:
  - 1.11.x
script: make test

services:
  - mysql

dist: bionic
#addons:
#  apt:
#    sources:
#      - mysql-5.7-bionic
#    packages:
#      - mysql-server

sudo: required

before_script:
  - mysql -u muxi --password="muxi" < db.sql
