runmode: debug               # 开发模式, debug, release, test 部署时环境变量覆盖
addr: :4096                  # HTTP绑定端口
name: muxikstack              # API Server的名字
url: http://127.0.0.1:4096   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: muxikestackmuxistudiomuxiniubi
grade_crawl: "on"      # 获取个人课程时成绩是否爬取
log:
  writers: file,stdout # 部署时输出到 stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:  # DB 配置 部署时环境变量覆盖
  name: muxikstack
  addr: 127.0.0.1:3306
  username: muxi
  password: 123
oss:
  access_key:
  secret_key:
  bucket_name:
  domain_name:
default_user:
  avatar: https://avatars2.githubusercontent.com/u/43539191?s=460&v=4
  username: muxike
