// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-11-14 21:10:28.261265127 +0800 CST m=+0.071436291

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comment/{id}/": {
            "post": {
                "tags": [
                    "comment"
                ],
                "summary": "回复评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "回复的评论对象id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/comment.newCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CommentInfo"
                        }
                    }
                }
            }
        },
        "/comment/{id}/like/": {
            "put": {
                "tags": [
                    "comment"
                ],
                "summary": "评论点赞/取消点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "点赞评论id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/comment.likeDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.likeDataResponse"
                        }
                    }
                }
            }
        },
        "/evaluation/": {
            "get": {
                "tags": [
                    "comment"
                ],
                "summary": "评课广场获取评课列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游客登录则不需要此字段或为空",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "最大的一级评论数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "上一次请求的最后一个评课的id，若是初始请求则为0",
                        "name": "lastEvaluationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.playgroundResponse"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "comment"
                ],
                "summary": "发布评课",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/comment.evaluationPublishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.evaluationPublishResponse"
                        }
                    }
                }
            }
        },
        "/evaluation/{id}/": {
            "get": {
                "tags": [
                    "comment"
                ],
                "summary": "获取评课详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游客登录则不需要此字段或为空",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "评课id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.EvaluationInfo"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "comment"
                ],
                "summary": "删除评课",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评课id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/evaluation/{id}/comment/": {
            "post": {
                "tags": [
                    "comment"
                ],
                "summary": "评论评课",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评课id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/comment.newCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ParentCommentInfo"
                        }
                    }
                }
            }
        },
        "/evaluation/{id}/comments/": {
            "get": {
                "tags": [
                    "comment"
                ],
                "summary": "评论点赞/取消点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游客登录则不需要此字段或为空",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "评课id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "最大的一级评论数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "翻页页码，默认为0",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.commentListResponse"
                        }
                    }
                }
            }
        },
        "/evaluation/{id}/like/": {
            "put": {
                "tags": [
                    "comment"
                ],
                "summary": "评论点赞/取消点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "点赞的评课id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/comment.likeDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.likeDataResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用学号登录，返回token，如果isnew==1，就要post用户信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "学号登录",
                "parameters": [
                    {
                        "description": "sid学号，password密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.LoginModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AuthResponse"
                        }
                    }
                }
            }
        },
        "/message/": {
            "get": {
                "tags": [
                    "message"
                ],
                "summary": "获取消息提醒",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页最大数",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/message.messageListResponse"
                        }
                    }
                }
            }
        },
        "/table/": {
            "get": {
                "tags": [
                    "table"
                ],
                "summary": "获取课表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/table.getTablesResponse"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "table"
                ],
                "summary": "新建课表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "若是创建副本，则为课表副本id，若是添加新课表，则为空",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ClassTableInfo"
                        }
                    }
                }
            }
        },
        "/table/{id}/": {
            "delete": {
                "tags": [
                    "table"
                ],
                "summary": "删除课表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课表id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/table/{id}/class/": {
            "post": {
                "tags": [
                    "table"
                ],
                "summary": "收藏的课堂加入课表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课表id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课堂id",
                        "name": "classId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/table.addClassResponseData"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "table"
                ],
                "summary": "删除课堂",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课表id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课堂id",
                        "name": "classId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/table/{id}/rename/": {
            "put": {
                "tags": [
                    "table"
                ],
                "summary": "课表重命名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课表id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/table.renameBodyData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/tag/": {
            "get": {
                "tags": [
                    "tag"
                ],
                "summary": "获取课程评价标签列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tag.tagGetResponse"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "description": "带着token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserInfoResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "带着token，上传用户的头像/avatar，名字/username.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "上传用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.UserInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "comment.commentListResponse": {
            "type": "object",
            "properties": {
                "parent_comment_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ParentCommentInfo"
                    }
                },
                "parent_comment_num": {
                    "type": "integer"
                }
            }
        },
        "comment.evaluationPublishRequest": {
            "type": "object",
            "required": [
                "attendance_check_type",
                "content",
                "course_id",
                "course_name",
                "exam_check_type",
                "is_anonymous",
                "rate",
                "tags"
            ],
            "properties": {
                "attendance_check_type": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "course_id": {
                    "type": "string"
                },
                "course_name": {
                    "type": "string"
                },
                "exam_check_type": {
                    "type": "integer"
                },
                "is_anonymous": {
                    "type": "boolean"
                },
                "rate": {
                    "type": "number"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "comment.evaluationPublishResponse": {
            "type": "object",
            "properties": {
                "evaluation_id": {
                    "type": "integer"
                }
            }
        },
        "comment.likeDataRequest": {
            "type": "object",
            "properties": {
                "is_like": {
                    "type": "boolean"
                }
            }
        },
        "comment.likeDataResponse": {
            "type": "object",
            "properties": {
                "is_like": {
                    "type": "boolean"
                },
                "like_num": {
                    "type": "integer"
                }
            }
        },
        "comment.newCommentRequest": {
            "type": "object",
            "required": [
                "content",
                "is_anonymous"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_anonymous": {
                    "type": "boolean"
                }
            }
        },
        "comment.playgroundResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.EvaluationInfo"
                    }
                },
                "sum": {
                    "type": "integer"
                }
            }
        },
        "message.messageListResponse": {
            "type": "object",
            "properties": {
                "messageList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MessageSub"
                    }
                }
            }
        },
        "model.AuthResponse": {
            "type": "object",
            "properties": {
                "is_new": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "model.ClassInfo": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "string"
                },
                "class_name": {
                    "type": "string"
                },
                "course_id": {
                    "type": "string"
                },
                "places": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teacher": {
                    "type": "string"
                },
                "times": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClassTimeInfo"
                    }
                }
            }
        },
        "model.ClassTableInfo": {
            "type": "object",
            "properties": {
                "class_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClassInfo"
                    }
                },
                "class_num": {
                    "type": "integer"
                },
                "table_id": {
                    "type": "integer"
                },
                "table_name": {
                    "type": "string"
                }
            }
        },
        "model.ClassTimeInfo": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "integer"
                },
                "duration": {
                    "type": "integer"
                },
                "start": {
                    "type": "integer"
                },
                "week_state": {
                    "description": "全周0,单周1,双周2",
                    "type": "integer"
                },
                "weeks": {
                    "type": "string"
                }
            }
        },
        "model.CommentInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_anonymous": {
                    "type": "boolean"
                },
                "is_like": {
                    "type": "boolean"
                },
                "like_num": {
                    "type": "integer"
                },
                "target_user_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.UserInfoResponse"
                },
                "time": {
                    "type": "string"
                },
                "user_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.UserInfoResponse"
                }
            }
        },
        "model.CourseInfo": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "comment_course_id": {
                    "type": "integer"
                },
                "course_name": {
                    "type": "string"
                }
            }
        },
        "model.EvaluationInfo": {
            "type": "object",
            "properties": {
                "attendance_check_type": {
                    "type": "string"
                },
                "comment_num": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "course_id": {
                    "type": "string"
                },
                "course_name": {
                    "type": "string"
                },
                "exam_check_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_anonymous": {
                    "type": "boolean"
                },
                "is_like": {
                    "type": "boolean"
                },
                "like_num": {
                    "type": "integer"
                },
                "rate": {
                    "type": "number"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teacher": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "user_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.UserInfoResponse"
                }
            }
        },
        "model.LoginModel": {
            "type": "object",
            "required": [
                "password",
                "sid"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                }
            }
        },
        "model.MessageSub": {
            "type": "object",
            "properties": {
                "course_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.CourseInfo"
                },
                "is_like": {
                    "type": "boolean"
                },
                "is_read": {
                    "type": "boolean"
                },
                "reply": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "user_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.UserInfoRequest"
                }
            }
        },
        "model.ParentCommentInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "description": "父评论id",
                    "type": "string"
                },
                "is_anonymous": {
                    "type": "boolean"
                },
                "is_like": {
                    "type": "boolean"
                },
                "like_num": {
                    "type": "integer"
                },
                "sub_comments_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CommentInfo"
                    }
                },
                "sub_comments_num": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "user_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.UserInfoResponse"
                }
            }
        },
        "model.TagModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "tagName": {
                    "type": "string"
                }
            }
        },
        "model.UserInfoRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserInfoResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "table.addClassResponseData": {
            "type": "object",
            "properties": {
                "class_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.ClassInfo"
                },
                "table_id": {
                    "type": "integer"
                }
            }
        },
        "table.getTablesResponse": {
            "type": "object",
            "properties": {
                "table_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClassTableInfo"
                    }
                },
                "table_num": {
                    "type": "integer"
                }
            }
        },
        "table.renameBodyData": {
            "type": "object",
            "properties": {
                "new_name": {
                    "type": "string"
                }
            }
        },
        "tag.tagGetResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TagModel"
                    }
                },
                "sum": {
                    "type": "integer"
                }
            }
        }
    },
    "tags": [
        {
            "description": "用户相关",
            "name": "user"
        },
        {
            "description": "消息提醒",
            "name": "message"
        },
        {
            "description": "课程相关",
            "name": "course"
        },
        {
            "description": "评课\u0026评论",
            "name": "comment"
        },
        {
            "description": "排课课表",
            "name": "table"
        },
        {
            "description": "举报",
            "name": "report"
        },
        {
            "description": "课程评价标签",
            "name": "tag"
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "...",
	BasePath:    "/api/v1",
	Schemes:     []string{"https"},
	Title:       "Muxi K-Stack",
	Description: "木犀课栈",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
